language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_install:
  - composer self-update
  - mkdir /home/travis/build/mindgruve/derby/src/Tests/Integration/Temp
install:
  - composer install
script: 
  - ./run-tests.sh



