derby:
  defaults:
    media:      'Derby\Media'
    file:       'Derby\Media\File'
    embed:      'Derby\Media\Embed'
    collection: 'Derby\Media\Collection'
    alias:      'Derby\Media\Alias'
  thumbnails:
    library:      'Imagine\Imagick\Imagine'
    localAdapter: 'Derby\Media\Adapter\LocalAdapter'
    webAdapter:   'Derby\Media\Adapter\WebAdapter'
  adapter:
    - {
        class: 'Derby\Media\Adapter\YouTubeAdapter',
        name: 'youtube'
      }
    - {
        class: 'Derby\Media\Adapter\FlickrAdapter',
        name: 'flickr'
      }    
    - {
        class: 'Derby\Media\Adapter\OpenCloudAdapter',
        name: 'opencloud'
      }   
  media:
    - { 
        class: 'Derby\Media\File\Audio',
        extensions: [ 'mp3', 'wav', 'wma' ],   
        mime_types: [ 'audio/mpeg',  'audio/vnd.wave', 'audio/wav', 'audio/wave',  'audio/x-wav' ],
        adapter: 'opencloud'
      }
    - { 
        class: 'Derby\Media\File\Document', 
        extensions: [ 'doc', 'rtf', 'txt' ],  
        mime_types: [ 'application/msword', 'text/rtf', 'application/rtf', 'text/plain' ],
        adapter: 'opencloud'
      }
    - {
        class: 'Derby\Media\File\Image',    
        extensions: [ 'jpg', 'jpeg', 'gif', 'bmp', 'png' ],  
        mime_types: [ 'image/jpeg', 'image/gif', 'image/bmp', 'image/x-bmp', 'image/png' ],
        adapter: 'opencloud'
      }
    - { 
        class: 'Derby\Media\File\Pdf',      
        extensions: [ 'pdf' ],  
        mime_types: [ 'application/pdf', 'application/x-pdf' ],
        adapter: 'opencloud'
      }
    - { 
        class: 'Derby\Media\File\Presentation',
        extensions: [ 'ppt','pptx' ],
        mime_types: [ 'application/vnd.ms-powerpointtd>', 'application/vnd.openxmlformats-officedocument.presentationml.presentation' ],
        adapter: 'opencloud'
      }
    - {
        class: 'Derby\Media\File\Spreadsheet',  
        extensions: [ 'xls', 'xlsx', 'xlsm' ],
        mime_types: [ 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel.sheet.macroEnabled.12' ],
        adapter: 'opencloud'
      }
    - {
        class: 'Derby\Media\File\Video',  
        extensions: [ 'webm', 'vob', 'ogg', 'wmv', 'avi', 'mov', 'qt', 'mp4', 'mpg',  'mpeg' ],
        mime_types: [ 'video/webm', 'video/dvd',  'video/mpeg', 'video/x-ms-vob', 'video/ogg', 'application/ogg', 'video/vnd.avi', 'video/avi', 'video/msvideo', 'video/x-msvideo', 'video/quicktime', 'video/x-ms-wmv', 'video/mp4', 'video/mpeg' ],
        adapter: 'opencloud'
      }
    - {
        class: 'Derby\Media\File',  
        extensions: [ '*' ],
        mime_types: [ '*' ],
        adapter: 'opencloud'
      }
