parameters:
    media.tmp_path: /tmp/derby


services:
    imagine.imagick:
        class: Imagine\Imagick\Imagine
    imagine.gd:
        class: Imagine\Gd\Imagine
    imagine.Gmagick:
        class: Imagine\Gmagick\Imagine
    media.adapter.local_file:
        class: Derby\Adapter\LocalFileAdapter
        arguments: [ %media.tmp_path%, false, '0777' ]
    media.factory.audio:
        class: Derby\Media\LocalFile\Factory\AudioFactory
        arguments:
            - [ 'mp3', 'wav', 'wma' ]
            - [ 'audio/mpeg',  'audio/vnd.wave', 'audio/wav', 'audio/wave',  'audio/x-wav' ]
    media.factory.document:
        class: Derby\Media\LocalFile\Factory\DocumentFactory
        arguments:
            - [ 'doc', 'rtf' ]
            - [ 'application/msword', 'text/rtf', 'application/rtf' ]
    media.factory.html:
        class: Derby\Media\LocalFile\Factory\HtmlFactory
        arguments:
            - [ 'html' ]
            - [ 'text/plain', 'txt/html' ]
    media.factory.image:
        class: Derby\Media\LocalFile\Factory\ImageFactory
        arguments:
            - [ 'jpg', 'jpeg', 'gif', 'bmp', 'png' ]
            - [ 'image/jpeg', 'image/gif', 'image/bmp', 'image/x-bmp', 'image/png' ]
            - @imagine.imagick
    media.factory.local:
        class: Derby\Media\LocalFile\Factory\LocalFactory
        arguments:
            - [ '*' ]
            - [ '*' ]
    media.factory.pdf:
        class: Derby\Media\LocalFile\Factory\PdfFactory
        arguments:
            - [ 'pdf' ]
            - [ 'application/pdf', 'application/x-pdf' ]
    media.factory.presentation:
        class: Derby\Media\LocalFile\Factory\PresentationFactory
        arguments:
            - [ 'ppt', 'pptx' ]
            - [ 'application/vnd.ms-powerpointtd>', 'application/vnd.openxmlformats-officedocument.presentationml.presentation' ]
    media.factory.spreadsheet:
        class: Derby\Media\LocalFile\Factory\SpreadsheetFactory
        arguments:
            - [ 'xls', 'xlsx', 'xlsm' ]
            - [ 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel.sheet.macroEnabled.12' ]
    media.factory.text:
        class: Derby\Media\LocalFile\Factory\TextFactory
        arguments:
            - [ 'txt' ]
            - [ 'text/plain' ]
    media.factory.video:
        class: Derby\Media\LocalFile\Factory\VideoFactory
        arguments:
            - [ 'webm', 'vob', 'ogg', 'wmv', 'avi', 'mov', 'qt', 'mp4', 'mpg',  'mpeg' ]
            - [ 'video/webm', 'video/dvd',  'video/mpeg', 'video/x-ms-vob', 'video/ogg', 'application/ogg', 'video/vnd.avi', 'video/avi', 'video/msvideo', 'video/x-msvideo', 'video/quicktime', 'video/x-ms-wmv', 'video/mp4', 'video/mpeg' ]