parameters:
    media.tmp_path: /tmp/derby
    media.filters:
        square-outbound:
          filter: { resize: { height: 200, width: 200, quality: 80, mode: outbound } }
        square-inset:
          filter: { resize: { height: 200, width: 200, quality: 80, mode: inset } }
        greyscale:
          filter: { greyscale: true }
        flip-vertically:
          filter: { flipVertically: true }
        flip-horizontally:
          filter: { flipVertically: true }
        rotate-90:
          filter: { rotate: { degrees: 90 } }

services:
    # Media Manager
    media.manager:
        class: Derby\MediaManager

    # Imagine
    imagine.imagick:
        class: Imagine\Imagick\Imagine
    imagine.gd:
        class: Imagine\Gd\Imagine
    imagine.Gmagick:
        class: Imagine\Gmagick\Imagine

    # Gaufrette Adapters
    gaufrette.adapter.local:
        class: Gaufrette\Adapter\Local
        arguments: [ %media.tmp_path%, false, '0777' ]

    # Media Adapters
    media.adapter.local_file:
        class: Derby\Adapter\FileAdapter
        arguments: [ @gaufrette.adapter.local ]
        tags:
            - { name: media.adapter, key: temp }

    # Media Factories
    media.factory.audio:
        class: Derby\Media\File\Factory\AudioFactory
        arguments:
            - [ 'mp3', 'wav', 'wma' ]
        tags:
            - { name: media.factory, priority: 10 }
    media.factory.document:
        class: Derby\Media\File\Factory\DocumentFactory
        arguments:
            - [ 'doc', 'rtf' ]
        tags:
            - { name: media.factory, priority: 10 }
    media.factory.html:
        class: Derby\Media\File\Factory\HtmlFactory
        arguments:
            - [ 'html' ]
        tags:
            - { name: media.factory, priority: 10 }
    media.factory.image:
        class: Derby\Media\File\Factory\ImageFactory
        arguments:
            - [ 'jpg', 'jpeg', 'gif', 'bmp', 'png' ]
            - @imagine.gd
        tags:
            - { name: media.factory, priority: 10 }
    media.factory.pdf:
        class: Derby\Media\File\Factory\PdfFactory
        arguments:
            - [ 'pdf' ]
        tags:
            - { name: media.factory, priority: 10 }
    media.factory.zip:
        class: Derby\Media\File\Factory\ZipFactory
        arguments:
            - [ 'zip' ]
        tags:
            - { name: media.factory, priority: 10 }
    media.factory.presentation:
        class: Derby\Media\File\Factory\PresentationFactory
        arguments:
            - [ 'ppt', 'pptx' ]
        tags:
            - { name: media.factory, priority: 10 }
    media.factory.spreadsheet:
        class: Derby\Media\File\Factory\SpreadsheetFactory
        arguments:
            - [ 'xls', 'xlsx', 'xlsm' ]
        tags:
            - { name: media.factory, priority: 10 }
    media.factory.text:
        class: Derby\Media\File\Factory\TextFactory
        arguments:
            - [ 'txt' ]
        tags:
            - { name: media.factory, priority: 10 }
    media.factory.video:
        class: Derby\Media\File\Factory\VideoFactory
        arguments:
            - [ 'webm', 'vob', 'ogg', 'wmv', 'avi', 'mov', 'qt', 'mp4', 'mpg',  'mpeg' ]
        tags:
            - { name: media.factory, priority: 10 }
    media.factory.file:
        class: Derby\Media\File\Factory\FileFactory
        arguments:
            - [ '*' ]
        tags:
            - { name: media.factory, priority: 100 }